FROM alpine

LABEL container.maintainer="zyqcn@live.com"

RUN apk add --no-cache tzdata

RUN apk --no-cache add wireguard-tools



创建容器
删除
重启

1.主机表增加在线离线状态，主机表增加在线状态，定时任务检测节点状态（频率待定）

2.获取端口增加主机分布式锁，防止并发操作，
锁开始：创建容器开始
锁开始：创建容器完成（）


3.创建容器失败数据不一致
增加事务，创建容器失败回滚事务，增加容器删除缓存，定时扫描删除容器



4.删除容器、重启容器

先删容器表，where status != 绑定中和已绑定


k8s删除  --删除成功，返回失败了
       --删除失败

删除容器主机关联表

5.分配容器













