apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-k8s
  namespace: default
data:
  TAILSCALE_HOSTNAME: "tailscale-k8s"
  TAILSCALE_ADVERTISE_ROUTES: "10.96.0.0/12"
  TAILSCALE_ADVERTISE_TAGS: ""
  TAILSCALE_ACCEPT_DNS: "true"
  TAILSCALE_ACCEPT_ROUTES: "false"
  TAILSCALE_ADVERTISE_EXIT_NODES: "false"
  TAILSCALE_EXIT_NODE_ALLOW_LAN_ACCESS: "false"
  TAILSCALE_EXIT_NODE: "false"
  TAILSCALE_FORCE_REAUTH: "false"
  TAILSCALE_HOST_ROUTES: "true"
  TAILSCALE_LOGIN_SERVER: "https://login.tailscale.com"
  TAILSCALE_NETFILTER_MODE: "auto"
  TAILSCALE_QR: "false"
  TAILSCALE_SHIELDS_UP: "false"
  TAILSCALE_SNAT_SUBNET_ROUTES: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-secret
type: Opaque
data:
  auth-key: xxxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-k8s
  template:
    metadata:
      labels:
        app: tailscale-k8s
    spec:
      containers:
        - name: tailscale-k8s
          image: zouyq/tailscale-k8s
          imagePullPolicy: IfNotPresent
          env:
            - name: TAILSCALE_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-secret
                  key: auth-key
            - name: TAILSCALE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_HOSTNAME
            - name: TAILSCALE_ADVERTISE_ROUTES
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_ADVERTISE_ROUTES
            - name: TAILSCALE_ADVERTISE_TAGS
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_ADVERTISE_TAGS
            - name: TAILSCALE_ACCEPT_DNS
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_ACCEPT_DNS
            - name: TAILSCALE_ACCEPT_ROUTES
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_ACCEPT_ROUTES
            - name: TAILSCALE_ADVERTISE_EXIT_NODES
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_ADVERTISE_EXIT_NODES
            - name: TAILSCALE_EXIT_NODE_ALLOW_LAN_ACCESS
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_EXIT_NODE_ALLOW_LAN_ACCESS
            - name: TAILSCALE_EXIT_NODE
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_EXIT_NODE
            - name: TAILSCALE_FORCE_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_FORCE_REAUTH
            - name: TAILSCALE_HOST_ROUTES
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_HOST_ROUTES
            - name: TAILSCALE_LOGIN_SERVER
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_LOGIN_SERVER
            - name: TAILSCALE_NETFILTER_MODE
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_NETFILTER_MODE
            - name: TAILSCALE_QR
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_QR
            - name: TAILSCALE_SHIELDS_UP
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_SHIELDS_UP
            - name: TAILSCALE_SNAT_SUBNET_ROUTES
              valueFrom:
                configMapKeyRef:
                  name: tailscale-k8s
                  key: TAILSCALE_SNAT_SUBNET_ROUTES
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN