name: build-netbird
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 0 1 *"
  workflow_dispatch:
env:
  base_directory: zouyq
  target_directory: netbird

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [ 'netbird', 'netbird-mgmt','netbird-signal','netbird-dashboard' ] }

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.base_directory }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower case
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.base_directory }}/${{ matrix.dir }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.base_directory }}/${{ env.target_directory }}/${{ matrix.dir }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ steps.string.outputs.lowercase }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
