# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
  # Show how to print unmasked GitHub secrets to the console
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.DOCKER_USERNAME }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.PACKAGES_TOKEN}} | sed 's/./& /g' 
  
